/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AutoscalingSettingsV1
 */
public class AutoscalingSettingsV1Test {
    private final AutoscalingSettingsV1 model = new AutoscalingSettingsV1();

    /**
     * Model tests for AutoscalingSettingsV1
     */
    @Test
    public void testAutoscalingSettingsV1() {
        // TODO: test AutoscalingSettingsV1
    }

    /**
     * Test the property 'minReplica'
     */
    @Test
    public void minReplicaTest() {
        // TODO: test minReplica
    }

    /**
     * Test the property 'maxReplica'
     */
    @Test
    public void maxReplicaTest() {
        // TODO: test maxReplica
    }

    /**
     * Test the property 'autoscalingWindow'
     */
    @Test
    public void autoscalingWindowTest() {
        // TODO: test autoscalingWindow
    }

    /**
     * Test the property 'scaleDownDelay'
     */
    @Test
    public void scaleDownDelayTest() {
        // TODO: test scaleDownDelay
    }

    /**
     * Test the property 'concurrencyTarget'
     */
    @Test
    public void concurrencyTargetTest() {
        // TODO: test concurrencyTarget
    }

}
