/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AutoscalingSettingsV1;
import com.konfigthis.client.model.DeploymentStatusV1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeploymentV1
 */
public class DeploymentV1Test {
    private final DeploymentV1 model = new DeploymentV1();

    /**
     * Model tests for DeploymentV1
     */
    @Test
    public void testDeploymentV1() {
        // TODO: test DeploymentV1
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'isProduction'
     */
    @Test
    public void isProductionTest() {
        // TODO: test isProduction
    }

    /**
     * Test the property 'isDevelopment'
     */
    @Test
    public void isDevelopmentTest() {
        // TODO: test isDevelopment
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'activeReplicaCount'
     */
    @Test
    public void activeReplicaCountTest() {
        // TODO: test activeReplicaCount
    }

    /**
     * Test the property 'autoscalingSettings'
     */
    @Test
    public void autoscalingSettingsTest() {
        // TODO: test autoscalingSettings
    }

}
