/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelV1
 */
public class ModelV1Test {
    private final ModelV1 model = new ModelV1();

    /**
     * Model tests for ModelV1
     */
    @Test
    public void testModelV1() {
        // TODO: test ModelV1
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'deploymentsCount'
     */
    @Test
    public void deploymentsCountTest() {
        // TODO: test deploymentsCount
    }

    /**
     * Test the property 'productionDeploymentId'
     */
    @Test
    public void productionDeploymentIdTest() {
        // TODO: test productionDeploymentId
    }

    /**
     * Test the property 'developmentDeploymentId'
     */
    @Test
    public void developmentDeploymentIdTest() {
        // TODO: test developmentDeploymentId
    }

    /**
     * Test the property 'instanceTypeName'
     */
    @Test
    public void instanceTypeNameTest() {
        // TODO: test instanceTypeName
    }

}
