/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PromoteRequestV1
 */
public class PromoteRequestV1Test {
    private final PromoteRequestV1 model = new PromoteRequestV1();

    /**
     * Model tests for PromoteRequestV1
     */
    @Test
    public void testPromoteRequestV1() {
        // TODO: test PromoteRequestV1
    }

    /**
     * Test the property 'scaleDownPreviousProduction'
     */
    @Test
    public void scaleDownPreviousProductionTest() {
        // TODO: test scaleDownPreviousProduction
    }

}
