/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateAutoscalingSettingsStatusV1
 */
public class UpdateAutoscalingSettingsStatusV1Test {
    /**
     * Model tests for UpdateAutoscalingSettingsStatusV1
     */
    @Test
    public void testUpdateAutoscalingSettingsStatusV1() {
        // TODO: test UpdateAutoscalingSettingsStatusV1
    }

}
