/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The status of a deployment.
 */
@JsonAdapter(DeploymentStatusV1.Adapter.class)public enum DeploymentStatusV1 {
  
  BUILDING("BUILDING"),
  
  DEPLOYING("DEPLOYING"),
  
  DEPLOY_FAILED("DEPLOY_FAILED"),
  
  LOADING_MODEL("LOADING_MODEL"),
  
  ACTIVE("ACTIVE"),
  
  UNHEALTHY("UNHEALTHY"),
  
  BUILD_FAILED("BUILD_FAILED"),
  
  BUILD_STOPPED("BUILD_STOPPED"),
  
  DEACTIVATING("DEACTIVATING"),
  
  INACTIVE("INACTIVE"),
  
  FAILED("FAILED"),
  
  UPDATING("UPDATING"),
  
  SCALED_TO_ZERO("SCALED_TO_ZERO"),
  
  WAKING_UP("WAKING_UP");

  private String value;

  DeploymentStatusV1(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DeploymentStatusV1 fromValue(String value) {
    for (DeploymentStatusV1 b : DeploymentStatusV1.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DeploymentStatusV1> {
    @Override
    public void write(final JsonWriter jsonWriter, final DeploymentStatusV1 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DeploymentStatusV1 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DeploymentStatusV1.fromValue(value);
    }
  }
}

