/*
 * Baseten management API
 * REST API for management of Baseten resources
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.SecretV1;
import com.konfigthis.client.model.SecretsV1;
import com.konfigthis.client.model.UpsertSecretRequestV1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretApi
 */
@Disabled
public class SecretApiTest {

    private static SecretApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SecretApi(apiClient);
    }

    /**
     * Gets all secrets
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllSecretsTest() throws ApiException {
        SecretsV1 response = api.getAllSecrets()
                .execute();
        // TODO: test validations
    }

    /**
     * Upserts a secret
     *
     * Creates a new secret or updates an existing secret if one with the provided name already exists. The name and creation date of the created or updated secret is returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void upsertNewSecretTest() throws ApiException {
        String name = null;
        String value = null;
        SecretV1 response = api.upsertNewSecret(name, value)
                .execute();
        // TODO: test validations
    }

}
